### ISSUE TITLE
Failed to retrieve library!

### ISSUE THREAD

**Issue by 0x73am43l** [sharkwouter/minigalaxy#320] opened 2021-04-20 06:00 UTC
I get this warning when I open the app and it does not show the game list 
![w](https://user-images.githubusercontent.com/13575387/115345001-662f4280-a1c3-11eb-8147-d96aa0ef0fbf.png)

**Comment by sharkwouter** [comment] 2021-04-20 08:32
How many games for Linux do you have?

**Comment by makson96** [comment] 2021-06-14 20:21
This does look like duplicate of #271
Could you reproduce this issue with master branch?

**Comment by thexavier666** [comment] 2021-06-18 20:11
I am having the same issue @makson96 

```
minigalaxy --version
1.0.2
```

Resolved only after adding linux-compatible titles to account.
There should be a different error "No linux games present in account"

**Comment by makson96** [comment] 2021-06-19 07:17
@thexavier666 this issue is already addressed in the master branch.
I would like @0x73am43l to confirm it is the same issue before closing it.

**Comment by sharkwouter** [comment] 2021-11-08 22:20
This should be fixed in version 1.1.0

**Closed by sharkwouter** 2021-11-08 22:20 UTC
Labels: needs testing
