### ISSUE TITLE
No icons for already installed games

### ISSUE THREAD

**Issue by berarma** [sharkwouter/minigalaxy#110] opened 2020-03-31 14:55 UTC
After working around issue #109 my already installed games were found but the icon disappeared. Before they were found installed they had their icon.

I'm using the deb package version 0.9.3 in Debian 10.

**Comment by sharkwouter** [comment] 2020-03-31 21:53
That's odd, it should be downloading them. Did you start Minigalaxy with a working internet connection? How fast is your connection? Not that I expect that to be the reason, but I want to make sure to rule it out.

**Comment by berarma** [comment] 2020-04-01 08:52
It's weird because all icons were showing before I configured the game path and minigalaxy found the already installed games. When it found them it stopped showing their icons.

**Comment by sharkwouter** [comment] 2020-04-01 17:33
I was able to reproduce this on the latest code in git. I'll look into it.

**Comment by sharkwouter** [comment] 2020-04-06 07:17
This also affects showing the store page or not. I'm not creating a new issues for this, since the fix will be the same.

**Comment by sharkwouter** [comment] 2020-04-06 19:06
This should be fixed in master now.

**Closed** 2020-04-06 19:06 UTC
Labels: bug

**Comment by wnhre2ur8cxx8** [comment] 2020-12-16 12:37
This is still an issue. just installed 1.0 via AUR and the installed games show up but they are the only ones without icon.

**Comment by sharkwouter** [comment] 2020-12-16 15:10
Yeah, it isn't in the version in the AUR yet. It will be in the next release.
