### ISSUE TITLE
[Feature Request] GOG Galaxy multiplayer

### ISSUE THREAD

**Issue by Hydra-Spectre** [sharkwouter/minigalaxy#331] opened 2021-06-17 07:36 UTC
I really want to jump to Linux but I am worried that I can no longer play multiplayer with the GOG version of Stardew Valley and GWENT.
I hope that Galaxy multiplayer can be integrated into MiniGalaxy. After that, I would no longer have any qualms with going to Linux.

**Comment by sharkwouter** [comment] 2021-06-17 08:46
Thanks for the report. I'm not quite sure if this would be possible for us to do, but if someone would like to take a shot at it that would be very welcome.

**Comment by makson96** [comment] 2021-06-19 07:18
This seems to be duplicate of #177

**Comment by sharkwouter** [comment] 2021-06-19 20:44
Thanks @makson96! Closing this one as duplicate

**Closed by sharkwouter** 2021-06-19 20:44 UTC
Labels: enhancement
