### ISSUE TITLE
Specific game stuck "in queue"

### ISSUE THREAD

**Issue by fefniir** [sharkwouter/minigalaxy#484] opened 2022-05-02 20:13 UTC
Minigalaxy ver: 1.1.0

Specific game is "The Legend of Heros: Trails in the Sky". Only this game exhibits this behavior, all other games linux native or windows download correctly. Additionally, when minigalaxy is started from the console, attempting to install the game produces no error message.

**Comment by sharkwouter** [comment] 2022-05-03 10:18
Thanks for the report! Could you try running the code in the master branch to see if the issue is still there? I'm planning on doing a new release soon

**Comment by fefniir** [comment] 2022-05-03 14:21
I'm currently using the aur package @
https://aur.archlinux.org/packages/minigalaxy

There is also a "git" package @
https://aur.archlinux.org/packages/minigalaxy-git

Would trying the git version work?

**Comment by sharkwouter** [comment] 2022-05-03 14:33
Yes, that should work

**Comment by sharkwouter** [comment] 2022-05-03 15:17
Interesting, does that only happen if it did not get stuck before?

**Comment by fefniir** [comment] 2022-05-03 15:47
Ok, I'm thinking that not fully closing when starting from the console
might be a separate issue. I just opened minigalaxy from the console and
tried closing via the close window button (big red X in upper right corner
of window) and the same thing happened. Didn't even try and install
anything, just started and tried to close the app. I can open up a new
issue for that if necessary.

**Comment by ignapk** [comment] 2022-05-04 21:49
Metal Gear also gets stuck "in queue", both 1.1.0 and master

**Comment by sharkwouter** [comment] 2022-05-04 22:28
That's a shame. Thanks for the update

**Comment by Kzimir** [comment] 2022-05-15 20:31
@sharkwouter The problem is the same that i had month ago with Batman Arkham Asylum. We discussed about that on Discord.
The problem is in gametile.py/__download function. It stuck about "total_file_size" and md5sum.
Quote these call workaround the issue 
![Capture du 2022-05-15 22-30-50](https://user-images.githubusercontent.com/3606036/168492653-f12d960f-ded5-4544-9fb7-22ca339e8d5a.png)

**Comment by sharkwouter** [comment] 2022-05-16 12:16
Oh that is useful information. That would mean this is fixed on the master branch right now. @fefniir could you test is the workaround bby @Kzimir works?

**Comment by Kzimir** [comment] 2022-05-16 12:22
> Oh that is useful information. That would mean this is fixed on the master branch right now. @fefniir could you test is the workaround bby @Kzimir works?

In fact, it's not really fixed in master... Because even with your commit #470, i still have the issue.
Victor Vran game has this issue when i want to download/install the Windows version. No issue with Linux version.

**Comment by fefniir** [comment] 2022-05-16 12:26
Will do, as soon as I get back to the house.

**Comment by sharkwouter** [comment] 2022-05-16 12:46
That is really interesting, then there is still a scenario which is not included in the tests at the moment. I'll have to investigate, especially if your work around works.

**Comment by sharkwouter** [comment] 2022-05-19 08:07
I'm going to keep this open to better track it, as there is no fix for it in master yet.

**Comment by fefniir** [comment] 2022-05-19 13:21
Oh, before I forget. Some additional info, that may or may not be relevant:

The, previously mentioned, download delay seems to be highly variable. I have downloaded that game 3 times in the last 24 hours. The first took about 5 minutes to start, the 2nd about 30 seconds, and the 3rd time time took about 15 minutes.

**Comment by iojeda** [comment] 2022-06-12 18:52
Hi Guys, I also have this issue.
I am trying to download Chorvs and it gets stucked in queue.
I tested running the app from the command line to see if I could get additional info.
This is the error I get maybe it helps...
![image](https://user-images.githubusercontent.com/5243583/173248763-4d265da7-a7bd-41f1-b6db-c3a791f64816.png)

**Comment by iojeda** [comment] 2022-06-12 19:00
![image](https://user-images.githubusercontent.com/5243583/173249080-528c984e-4429-48a7-b54a-ed64424917f2.png)

**Comment by zelurker** [comment] 2022-06-15 18:56
The issue is still here for the chaotic-aur package in arch.
I applied the patch directly, commented the total_file_size line -> no change
commented the md5sum line -> download finally starts !
It was for daggerfall unity.

**Comment by sharkwouter** [comment] 2022-06-23 02:47
I've made some more adjustments which should fix this issue. Could anyone do a test on the master branch?

**Comment by sharkwouter** [comment] 2022-06-24 15:36
Thanks for testing. I'll try some other things. I'm having a hard time reproducing this, as I don't have the games mentioned in this thread. I'll try to see if I can find more games with this issue.

**Comment by joshuashort** [comment] 2022-07-30 07:41
> Thanks for testing. I'll try some other things. I'm having a hard time reproducing this, as I don't have the games mentioned in this thread. I'll try to see if I can find more games with this issue.

I just found this amazing project; and found that many of my few games seem to fit this general issue. A couple: Baldur's Gate 3; The Witcher 3.

Using the current master branch, modifying download_manager.py:download_operation to

```python
    def download_operation(self, download, start_point, download_mode):
        # Download the file
        resume_header = {'Range': 'bytes={}-'.format(start_point)}
        download_request = SESSION.get(download.url, headers=resume_header, stream=True, timeout=30)
        downloaded_size = start_point
        file_size = download_request.headers.get('content-length')  # sometimes this header is None..
        if file_size is not None:
            file_size = int(file_size)  # there's probably a better way (or a root cause?)
        result = True
        if (file_size is None) or (downloaded_size < file_size):  # it might be a bigger deal, but force to continue
            with open(download.save_location, download_mode) as save_file:
                for chunk in download_request.iter_content(chunk_size=DOWNLOAD_CHUNK_SIZE):
                    # Pause if needed
                    while self.__paused:
                        time.sleep(0.1)
                    save_file.write(chunk)
                    downloaded_size += len(chunk)
                    if self.__cancel:
                        result = False
                        break
                    if (file_size is None) or (file_size > 0):  # breaks some expectations ...
                        progress = int(downloaded_size / file_size * 100)  # ... here
                        download.set_progress(progress)
                save_file.close()
        else:
            download.set_progress(100)
        return result
```

seems to get things going, but it's probably a little too clumsy. Seems to be the same basic problem as some other issues -- the content-length header seems to be missing in some cases?

Before (e.g.):
```
Exception in thread Thread-50 (__download_file):
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/minigalaxy/minigalaxy/download_manager.py", line 86, in __download_file
    result = self.download_operation(download, start_point, download_mode)
  File "/opt/minigalaxy/minigalaxy/download_manager.py", line 134, in download_operation
    file_size = int(download_request.headers.get('content-length'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by AeliusSaionji** [comment] 2022-08-14 20:16
Reporting in that Crypt of the Necrodancer has this problem!

**Comment by sharkwouter** [comment] 2022-09-05 15:36
Can anyone check if this issue still exist when using the branch `bugfix/484`?

**Closed** 2022-09-19 18:25 UTC
Labels: bug, needs testing, release critical

**Comment by fefniir** [comment] 2022-10-11 08:40
The console output? No idea, I can try with a game that does download and
see if it happens again.
