### ISSUE TITLE
Remove spaces and other characters from directory names (revert #98 fix)

### ISSUE THREAD

**Issue by mathieui** [sharkwouter/minigalaxy#148] opened 2020-04-29 17:08 UTC
Quite a few GOG games do not even start (due to sloppy bash scripts) when the original name (with spaces and everything) is used.

Some examples of games breaking due to this:

- Shadowrun: DragonFall
- Divinity: Original Sin
- AI War
- The Witcher 2

**Comment by sharkwouter** [comment] 2020-05-02 11:41
Oh that's a shame, thanks for reporting. I'll add it to the backlog for the next version. Have you tested renaming the directories manually?

**Comment by sharkwouter** [comment] 2020-09-13 13:33
I was not able to reproduce this issue with AI War anymore with the current code on master. For me The Witcher 2 does not install at all, but that seems to be an issue with unzip. I'm not sure how to deal with this.

Could you test if this is still a problem?

**Comment by larslindq** [comment] 2020-10-20 18:39
I tried to reproduce this as well.
I installed The Witcher 2 with 0.9.3 and the game launches. Then I installed 0.9.4 and the game still launches with the old name (TheWitcher2AssassinsofKingsEnhancedEdition).
I also installed The Witcher 2 with 0.9.4 and it launches as well with the new name (The Witcher 2: Assassins of Kings Enhanced Edition).

**Comment by sharkwouter** [comment] 2020-11-14 10:54
For now I'm going to assume this will be resolved with the next release. Please reopen if the next version (1.0.0) still has this issue.

**Closed by sharkwouter** 2020-11-14 10:54 UTC
Labels: bug, waiting for input
