### ISSUE TITLE
install on i386 systems error on game download due to unzip issue

### ISSUE THREAD

**Issue by SwampRabbit** [sharkwouter/minigalaxy#159] opened 2020-06-04 22:43 UTC
A user of MX Linux reported and I have confirmed that the following error stops game installation on i368 systems only.  This potentially affects Debian 10 as well, but I have not tested.

```
Resuming download /home/bob/.cache/minigalaxy/download/Tower of Time
Executing integrity check for /home/bob/.cache/minigalaxy/download/Tower of Time
Verifying archive integrity... MD5 checksums are OK. All good.
[/home/bob/.cache/minigalaxy/download/Tower of Time]
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [/home/bob/.cache/minigalaxy/download/Tower of Time]:  853359 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error: invalid zip file with overlapped components (possible zip bomb)
Failed to install Tower of Time: /home/bob/.cache/minigalaxy/download/Tower of Time could not be unzipped.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/minigalaxy/download.py", line 25, in finish
    self.__finish_func()
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 226, in __install
    install_game(self.game, self.download_path, parent_window=self.parent)
  File "/usr/lib/python3/dist-packages/minigalaxy/installer.py", line 33, in install_game
    raise CannotOpenZipContent(_("{} could not be unzipped.").format(installer))
minigalaxy.installer.CannotOpenZipContent: /home/bob/.cache/minigalaxy/download/Tower of Time could not be unzipped.
```
Searching for related bugs leads me to believe that the version of unzip used for Debian 10 has the issue, but I downloaded the version from Debian Testing which is fixed according to the changelog, but the symptom stays.

I do not know if it is an unzip, Debian, or minigalaxy issue; but it is limited to i386 only as running minigalaxy on MX-19 amd64 does not produce the issue.

**Comment by jmtd** [comment] 2020-08-04 21:30
How big is the ZIP?

**Comment by SwampRabbit** [comment] 2020-08-05 01:54
I honestly don’t remember it was so long ago, more have I had time to look
at it because it only affected one user who never returned to our forums is
I remember right.

I believe did talk to Wouter on Discord a bit about it, but nothing
conclusive came from it at the time.

If time frees up I can test again in a VM, but honestly right now dozens of
other packages have priority unless lots of 32bit MX users pop up asking
about it.

**Comment by jmtd** [comment] 2020-08-05 08:52
No worries it's not a problem for me in particular. I asked because if it was >4GiB that would explain the problem.

**Comment by SwampRabbit** [comment] 2020-08-05 21:44
Not sure what you are getting at, that shouldn’t be an issue here.  Note
the log - the file downloads fine and the checksum matches ok.

Any 4GB limitation is for RAM, not the File System on 32bit systems.

So unless unzip is trying to cram the whole thing into memory, I don’t
think it’s a problem.  If it was then everyone downloading a large game on
32bit systems would be throwing a fit right now.

All the being said, seems the specific game I was testing the user’s issue
with is 64bit Only so that’s a show stopper here.
But I think the user was trying a different game, but that could be 64bit
too.  Have to double check.

Still think all that is unrelated to the log output though.

**Comment by sharkwouter** [comment] 2020-09-03 21:24
This sounds a lot like an issue with unzip itself. I'm going to leave this open, but unless more people can confirm that they also have this issue, I'll probably not take a deep dive into it. On my 64 bit Debian installation I cannot reproduce it.

**Comment by SwampRabbit** [comment] 2020-09-05 03:08
@sharkwouter I'll see if I can reproduce it and report back, could be a few days though.

**Comment by sharkwouter** [comment] 2021-11-08 22:32
I'm going to close this one for now, since I've not seen any reports similar to it for a long time and I haven't been able to reproduce it myself.

**Closed by sharkwouter** 2021-11-08 22:32 UTC
Labels: needs testing

**Comment by SwampRabbit** [comment] 2021-11-09 01:32
@sharkwouter not a worry at all, my apologies for not doubling back on it, I'll be packaging the new release for the MX repos really soon anyway!
