### ISSUE TITLE
Add option to choose cache dir/use game installation path for extracting cache

### ISSUE THREAD

**Issue by rilian-la-te** [sharkwouter/minigalaxy#239] opened 2020-12-30 21:24 UTC
My home is 50 GiB. I cannot install Pathfinder:Kingmaker due to ~/.cache using both for 25 GiB download and more for extract. I am trying to install it to my 1.5 TiB /mnt/data, where all my big data lives (in Minigalaxy's options /mnt/data/Games set as install location).

Can you add option to set download/extract cache path like now with game installation path?

**Comment by makson96** [comment] 2021-01-01 15:42
As a workaround you can create symlink.
1. Remove ~/.cache/minigalaxy
2. Run: mkdir /mnt/data/minigalaxy_cache
3. Run: ln -s /mnt/data/minigalaxy_cache ~/.cache/minigalaxy

**Comment by makson96** [comment] 2021-01-01 15:46
This is duplicate of #120

**Comment by sharkwouter** [comment] 2021-01-12 22:04
I'm going to close this in favor of #120. Thanks for the report.

**Closed by sharkwouter** 2021-01-12 22:04 UTC
