### ISSUE TITLE
Some games are shown twice (version 1.0.2, Arch Linux)

### ISSUE THREAD

**Issue by sluedecke** [sharkwouter/minigalaxy#324] opened 2021-05-05 09:02 UTC
Two of my games are listed twice: Torchlight II (installed with mingalaxy) and Wasteland 2 DC (installed with offline installer before using minigalaxy).

Any idea how to solve this?

**Comment by sluedecke** [comment] 2021-05-10 18:57
turns out Torchlight actually is Torchlight and Torchlight II both using the same game icon.

**Comment by sharkwouter** [comment] 2021-05-12 08:08
Thanks for the report and the specific examples. I'll add it to the list for the next release.

**Comment by makson96** [comment] 2021-06-14 20:11
I think this issue is duplicate of #142

**Comment by sharkwouter** [comment] 2021-06-19 20:44
I'll keep this one open, since it mentions a specific game

**Comment by sharkwouter** [comment] 2021-08-20 21:22
This should be fixed on master now

**Closed by sharkwouter** 2021-08-20 21:22 UTC
Labels: bug
