### ISSUE TITLE
Can't install on Ubuntu 24.04 because of wrong dependencies

### ISSUE THREAD

**Issue by reneas** [sharkwouter/minigalaxy#608] opened 2024-08-18 09:53 UTC
When I try to install the latest release on my Kubuntu 24.04 system I'm getting this error message:
(same goes for the version from the official sources)
```
sudo apt install ./Programme/minigalaxy_1.3.0_all.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'minigalaxy' instead of './Programme/minigalaxy_1.3.0_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
gir1.2-webkit2-4.1 : Depends: libwebkit2gtk-4.1-0 (= 2.44.2-0ubuntu0.24.04.1) but 2.44.2-0ubuntu0.24.04.2 is to beinstalled
Depends: gir1.2-javascriptcoregtk-4.1 (= 2.44.2-0ubuntu0.24.04.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I think that only the updated versions in the dependencies have to be updated since `24.04.1` is required and `24.04.2` is the newer version.

When I'm running `sudo apt install libwebkit2gtk-4.1-0` I get:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libwebkit2gtk-4.1-0 is already the newest version (2.44.2-0ubuntu0.24.04.2).
libwebkit2gtk-4.1-0 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

And when running `sudo apt install gir1.2-javascriptcoregtk-4.1`

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
gir1.2-javascriptcoregtk-4.1 : Depends: libjavascriptcoregtk-4.1-0 (= 2.44.2-0ubuntu0.24.04.1) but 2.44.2-0ubuntu0.24.04.2 is to be installed
E: Unable to correct problems, you have held broken packages.
```
And finally when running `sudo apt install libjavascriptcoregtk-4.1-0`:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libjavascriptcoregtk-4.1-0 is already the newest version (2.44.2-0ubuntu0.24.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

So maybe i have to downgrade to the older version or the dependencies have ti be updated?

**Comment by sharkwouter** [comment] 2024-09-06 21:28
Hey @reneas, thanks for reporting this. I will look into it and do a release.

**Comment by sharkwouter** [comment] 2024-09-06 21:37
Okay, I looked into it a bit and Ubuntu 24.04 actually has the dependencies that are needed and the package installs fine in my test in docker. You could try running `apt-get install -f` to see if that fixes it.

**Comment by sharkwouter** [comment] 2024-12-12 10:42
I'm going to close this for now because I was not able to reproduce it.

**Closed by sharkwouter** 2024-12-12 10:42 UTC
